#!/bin/bash

PKA_HOME="/Users/sck/Code/pka"

source ${PKA_HOME}/functions.sh

sanity_check

case "$1" in
makekeystore)
	makekeystore
	;;
listapk)
	listapk
	;;
extract)
	extract "$2"
	;;
install)
	install
	;;
modinstall)
	modinstall
	;;
addmprof)
	addmprof "$2"
	;;
addbbprof)
	addbbprof "$2"
	;;
addvalprint)
	addvalprint "$2"
	;;
getmprof)
	get_mprof
	read_mprof
	;;
viewmprof)
	read_mprof
	;;
getbbprof)
	not_ready
	;;
viewbbprof)
	not_ready
	;;
reset)
	reset
	;;
backup)
	backup "$2"
	;;
restore)
	restore "$2"
	;;
clean)
	clean
	;;
cleanbackups)
	cleanbackups
	;;
nuke)
	clean
	cleanbackups
	;;
*)
	echo "Command not recognised."
	;;
esac
